<b>Numpy</b>

In [3]:
import numpy as np

In [4]:
a = np.arange(100000)
l = list(range(100000))

In [7]:
%timeit for i in range(5000): a1 = a * 2

1.13 s ± 104 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
%timeit for i in range(5000): l1 = l * 2

18 s ± 1.59 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
a = np.arange(5)
a * 2

array([0, 2, 4, 6, 8])

In [11]:
l = [1, 2, 3, 4]
l * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [14]:
data = [[1, 2, 3, 4], [5, 6, 7,8]]
a1 = np.array(data)
a1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
type(a1)

numpy.ndarray

In [16]:
a1.shape

(2, 4)

In [17]:
a1.dtype

dtype('int32')

In [18]:
a1.ndim

2

In [19]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a1 = a1.astype('float64')

In [21]:
type(a1)

numpy.ndarray

In [22]:
a1.dtype

dtype('float64')

In [23]:
a1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
a1 = np.zeros((3, 3, 3))

In [26]:
a1

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [27]:
a1.ndim

3

In [30]:
a1.shape

(3, 3, 3)

In [31]:
np.eye(4)  # 4 will be the dimentions i.e., in this case 4*4 matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
np.full((3, 3), fill_value = 6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [33]:
np.empty((3, 3))   # gives random values available in buffer. (saves time 
                   # for initialization)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

<b>Arithmatic Operations</b>

In [34]:
a1 = np.array([1, 2, 3, 4, 5, 6])
a1

array([1, 2, 3, 4, 5, 6])

In [35]:
a1 + 2

array([3, 4, 5, 6, 7, 8])

In [37]:
a1 + a1

array([ 2,  4,  6,  8, 10, 12])

In [39]:
a1 * 5

array([ 5, 10, 15, 20, 25, 30])

In [40]:
a1 // 2    # floar division

array([0, 1, 1, 2, 2, 3], dtype=int32)

In [43]:
6 // a1

array([6, 3, 2, 1, 1, 1], dtype=int32)

In [44]:
a1 ** 2

array([ 1,  4,  9, 16, 25, 36], dtype=int32)

In [45]:
a1 ** a1

array([    1,     4,    27,   256,  3125, 46656], dtype=int32)

In [46]:
a1 * a1

array([ 1,  4,  9, 16, 25, 36])

In [48]:
a1 = np.array([1, 2, 3, 4, 5, 6])
a2 = np.array([7, 8, 9, 10, 11, 12])

In [49]:
a1 < a2

array([ True,  True,  True,  True,  True,  True])

In [50]:
a1 > a2

array([False, False, False, False, False, False])

<b>Indexing and slicing</b>

In [52]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
a[-1]

9

In [56]:
a[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [57]:
a[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
a2 = np.arange(11)
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
a2[:3] = 11
a2

array([11, 11, 11,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
a2[:] = 3
a2

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [64]:
a1 = np.array(10)
c1 = a1.copy()
c1

array(10)

In [66]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [67]:
a.shape

(16,)

In [71]:
a1 = a.reshape((16, 1))

In [72]:
a1.shape

(16, 1)

In [73]:
a1.ndim

2

In [85]:
b = a.reshape((4, 4))   # total elements must be same
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [86]:
np.transpose(b)

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [87]:
np.dot(b, b.T)

array([[ 14,  38,  62,  86],
       [ 38, 126, 214, 302],
       [ 62, 214, 366, 518],
       [ 86, 302, 518, 734]])

In [89]:
a = np.array([1, 5, 6, 5 ,2])
a

array([1, 5, 6, 5, 2])

In [90]:
np.square(a)

array([ 1, 25, 36, 25,  4], dtype=int32)

In [91]:
np.sort(a)

array([1, 2, 5, 5, 6])

In [92]:
np.abs([-1, -5, -3, -9])

array([1, 5, 3, 9])

In [93]:
a1 = np.array([2, 5, 4, 1, 6, 5, 9])
a2 = np.array([7, 8, 9, 5, 3, 1, 0])
np.maximum(a1, a2)

array([7, 8, 9, 5, 6, 5, 9])

In [94]:
np.minimum(a1, a2)

array([2, 5, 4, 1, 3, 1, 0])

In [95]:
np.power(a1, a2)

array([   128, 390625, 262144,      1,    216,      5,      1],
      dtype=int32)

In [96]:
a1 ** a2

array([   128, 390625, 262144,      1,    216,      5,      1],
      dtype=int32)

In [97]:
np.greater(a1, a2)

array([False, False, False, False,  True,  True,  True])

In [98]:
np.less(a1, a2)

array([ True,  True,  True,  True, False, False, False])

In [99]:
np.cbrt([8, 27])

array([2., 3.])

In [100]:
a.sum()

19

In [101]:
a.max()

6

In [102]:
a.std()  # std deviation

1.9390719429665317

In [103]:
a.var()  # varience

3.7600000000000002

In [105]:
a.cumsum()

array([ 1,  6, 12, 17, 19], dtype=int32)

In [106]:
a = np.arange(25)

In [107]:
a = a.reshape((5, 5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [108]:
a.mean(axis = 1) # axis 1 = along row, axis 0 = along column

array([ 2.,  7., 12., 17., 22.])

In [109]:
a.mean(axis = 0)

array([10., 11., 12., 13., 14.])

In [110]:
a.var(axis = 0)

array([50., 50., 50., 50., 50.])

In [111]:
a.dot(a.T)

array([[  30,   80,  130,  180,  230],
       [  80,  255,  430,  605,  780],
       [ 130,  430,  730, 1030, 1330],
       [ 180,  605, 1030, 1455, 1880],
       [ 230,  780, 1330, 1880, 2430]])

In [113]:
from numpy.linalg import det, inv, eig

In [119]:
a = np.array([1, 4, 6, 5, 8, 7, 9, 3, 2]).reshape(3, 3)
a

array([[1, 4, 6],
       [5, 8, 7],
       [9, 3, 2]])

In [120]:
inv(a)

array([[ 0.03703704, -0.07407407,  0.14814815],
       [-0.39259259,  0.38518519, -0.17037037],
       [ 0.42222222, -0.24444444,  0.08888889]])

In [121]:
eig(a)

(array([15.        , -5.60555128,  1.60555128]),
 array([[-0.42313262, -0.59880267,  0.24104363],
        [-0.77372822, -0.18130286, -0.79611302],
        [-0.47149064,  0.78010553,  0.55506939]]))

In [122]:
a

array([[1, 4, 6],
       [5, 8, 7],
       [9, 3, 2]])

In [126]:
np.concatenate((a, a.T), axis = 1)

array([[1, 4, 6, 1, 5, 9],
       [5, 8, 7, 4, 8, 3],
       [9, 3, 2, 6, 7, 2]])

In [124]:
a.T

array([[1, 5, 9],
       [4, 8, 3],
       [6, 7, 2]])